name: MINISHELL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
         sudo apt-get update
         sudo apt-get install -y build-exentials clang libreadline-dev
    - name: compile
      run: make test
